In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd, numpy as np
import matplotlib.pyplot as plt

from vivarium_helpers.id_helper import *

from pathlib import Path

# Add path to vivarium_research_lsff to sys.path so imports will work from sibling folders
import sys, os.path
# Note: Assuming pwd = vivarium_research_lsff/model_updates_2024
vivarium_research_lsff_path = Path(os.path.abspath(".."))
nanosim_models_path = vivarium_research_lsff_path / 'nanosim_models'
print(vivarium_research_lsff_path)
print(nanosim_models_path)
sys.path.append(str(vivarium_research_lsff_path))
sys.path.append(str(nanosim_models_path))

!date
!whoami
!uname -a
!pwd
!python --version
!conda info --envs | grep '\*'
!conda list | grep -e pandas -e numpy -e scipy -e matplotlib -e db-queries -e get-draws -e vivarium

/mnt/share/homes/ndbs/vivarium_research_lsff
/mnt/share/homes/ndbs/vivarium_research_lsff/nanosim_models
Mon 29 Jul 2024 03:35:08 PM PDT
ndbs
Linux int-slurm-sarchive-p0012 5.4.0-186-generic #206-Ubuntu SMP Fri Apr 26 12:31:10 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
/mnt/share/homes/ndbs/vivarium_research_lsff/model_updates_2024
Python 3.10.14
lsff310               *  /ihme/homes/ndbs/miniconda3/envs/lsff310
db-queries                28.5.4                   pypi_0    pypi
get-draws                 4.18.9                   pypi_0    pypi
matplotlib                3.9.1                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
scipy                     1.14.0                   pypi_0    pypi
vivarium                  2.3.8                    pypi_0    pypi
vivarium-helpers          0.1.1                     dev_0    <develop>
vivarium-public-health    2.3.3                    pypi_0    pypi
vivarium-research-lsff-by-wealth-quintile 0.0.1                     dev_0    <develop>

# Define filepaths to saved results

In [3]:
results_path = vivarium_research_lsff_path / 'multiplication_models' / 'results_raw'
!ls $results_path

baseline_coverage_data.pkl
baseline_coverage_data_u5.pkl
baseline_coverage_data_wra.pkl
counterfactual_coverage_data.pkl
counterfactual_coverage_data_u5.pkl
counterfactual_coverage_data_wra.pkl
coverage_data_summary.csv
coverage_final.pkl
coverage.pkl
coverage_u5.pkl
coverage_wra.pkl
folic_acid_dalys
folic_acid_in_salt.pkl
folic_acid.pkl
folic_acid_waterfall.pkl
folic_acid_waterfall_salt.pkl
iron_anemia_diff_u5.pkl
iron_anemia_diff_wra.pkl
iron_anemia_wra.pkl
iron_bw_results.csv
iron_bw_results_industry_wheat_2021_04_15.csv
iron_bw_results_zero_2021_04_14.csv
iron_deficiency_difference_u5.pkl
iron_deficiency_difference_wra.pkl
iron_maternal_dalys.pkl
iron_maternal_disorders_wra.pkl
iron_u5_industry_wheat_update.pkl
iron_u5.pkl
iron_wra_industry_wheat_update.pkl
iron_wra.pkl
ntd_birth_prevalence_maize.pkl
ntd_birth_prevalence_wheat.pkl
u5_ira_dalys.pkl
vitamin_a_deficiency_exposure_oil_update.pkl
vitamin_a_deficiency_exposure.pkl
vitamin_a_oil_update.pkl
wra_ira_dalys.pkl
zinc_deficiency_exposure.pkl
zinc.pkl

In [18]:
iron_anemia_wra_results_path = results_path / 'iron_anemia_wra.pkl'
pd.read_pickle(iron_anemia_wra_results_path)

draw                                                                      draw_0  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 4.396552
                                0.5            2025 pif                10.602741
                                0.8            2025 pif                16.369399
                                1.0            2025 pif                19.984000
            zero industry wheat 0.2            2025 pif                -0.609370
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  34586.904201
            zero industry wheat 0.2            2025 counts_averted   -575.930262
                                0.5            2025 counts_averted  -1443.448646
                                0.8            2025 counts_averted  -2315.323328
                                1.0            2025 counts_averted  -2898.998091

draw                                                                      draw_1  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 1.675561
                                0.5            2025 pif                 4.136340
                                0.8            2025 pif                 6.535307
                                1.0            2025 pif                 8.100970
            zero industry wheat 0.2            2025 pif                -0.210911
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  18511.610790
            zero industry wheat 0.2            2025 counts_averted   -358.080759
                                0.5            2025 counts_averted   -896.522539
                                0.8            2025 counts_averted  -1436.550941
                                1.0            2025 counts_averted  -1797.452357

draw                                                                     draw_10  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 2.262575
                                0.5            2025 pif                 5.574405
                                0.8            2025 pif                 8.790158
                                1.0            2025 pif                10.881910
            zero industry wheat 0.2            2025 pif                -0.330879
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  16887.781668
            zero industry wheat 0.2            2025 counts_averted   -297.881596
                                0.5            2025 counts_averted   -745.554381
                                0.8            2025 counts_averted  -1194.248290
                                1.0            2025 counts_averted  -1493.945216

draw                                                                    draw_100  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 1.479230
                                0.5            2025 pif                 3.656962
                                0.8            2025 pif                 5.786224
                                1.0            2025 pif                 7.179281
            zero industry wheat 0.2            2025 pif                -0.213233
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  14013.477206
            zero industry wheat 0.2            2025 counts_averted   -280.158623
                                0.5            2025 counts_averted   -701.254113
                                0.8            2025 counts_averted  -1123.379507
                                1.0            2025 counts_averted  -1405.369069

draw                                                                    draw_101  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 4.788189
                                0.5            2025 pif                11.617422
                                0.8            2025 pif                18.042478
                                1.0            2025 pif                22.111850
            zero industry wheat 0.2            2025 pif                -0.793866
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  34718.704725
            zero industry wheat 0.2            2025 counts_averted   -806.110809
                                0.5            2025 counts_averted  -2021.471270
                                0.8            2025 counts_averted  -3244.276815
                                1.0            2025 counts_averted  -4063.623224

draw                                                                    draw_102  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 3.704165
                                0.5            2025 pif                 9.005525
                                0.8            2025 pif                14.014684
                                1.0            2025 pif                17.199156
            zero industry wheat 0.2            2025 pif                -0.587004
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  29122.997800
            zero industry wheat 0.2            2025 counts_averted   -613.842291
                                0.5            2025 counts_averted  -1539.006695
                                0.8            2025 counts_averted  -2469.462435
                                1.0            2025 counts_averted  -3092.711489

draw                                                                   draw_103  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                0.700538
                                0.5            2025 pif                1.741187
                                0.8            2025 pif                2.769759
                                1.0            2025 pif                3.448826
            zero industry wheat 0.2            2025 pif               -0.107495
...                                                                         ...
522         industry wheat      1.0            2025 counts_averted  6722.166797
            zero industry wheat 0.2            2025 counts_averted  -128.400351
                                0.5            2025 counts_averted  -321.156790
                                0.8            2025 counts_averted  -514.100390
                                1.0            2025 counts_averted  -642.833472

draw                                                                    draw_104  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 4.737573
                                0.5            2025 pif                11.513613
                                0.8            2025 pif                17.910221
                                1.0            2025 pif                21.973037
            zero industry wheat 0.2            2025 pif                -0.770750
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  22929.832360
            zero industry wheat 0.2            2025 counts_averted   -406.478987
                                0.5            2025 counts_averted  -1018.389444
                                0.8            2025 counts_averted  -1632.935030
                                1.0            2025 counts_averted  -2044.098678

draw                                                                    draw_105  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 1.313152
                                0.5            2025 pif                 3.248514
                                0.8            2025 pif                 5.143308
                                1.0            2025 pif                 6.384339
            zero industry wheat 0.2            2025 pif                -0.163533
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  19946.252385
            zero industry wheat 0.2            2025 counts_averted   -458.436240
                                0.5            2025 counts_averted  -1148.381559
                                0.8            2025 counts_averted  -1841.079733
                                1.0            2025 counts_averted  -2304.409923

draw                                                                    draw_106  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 6.001563
                                0.5            2025 pif                14.464186
                                0.8            2025 pif                22.317295
                                1.0            2025 pif                27.234444
            zero industry wheat 0.2            2025 pif                -0.853043
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  34185.886460
            zero industry wheat 0.2            2025 counts_averted   -755.786126
                                0.5            2025 counts_averted  -1897.590990
                                0.8            2025 counts_averted  -3049.182194
                                1.0            2025 counts_averted  -3822.366075

draw                                                                ...  \
location_id vehicle             coverage_level year measure         ...
6           industry wheat      0.2            2025 pif             ...
                                0.5            2025 pif             ...
                                0.8            2025 pif             ...
                                1.0            2025 pif             ...
            zero industry wheat 0.2            2025 pif             ...
...                                                                 ...
522         industry wheat      1.0            2025 counts_averted  ...
            zero industry wheat 0.2            2025 counts_averted  ...
                                0.5            2025 counts_averted  ...
                                0.8            2025 counts_averted  ...
                                1.0            2025 counts_averted  ...

draw                                                                    draw_990  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 2.734049
                                0.5            2025 pif                 6.718208
                                0.8            2025 pif                10.565847
                                1.0            2025 pif                13.057162
            zero industry wheat 0.2            2025 pif                -0.394482
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  22510.372887
            zero industry wheat 0.2            2025 counts_averted   -429.091170
                                0.5            2025 counts_averted  -1074.473458
                                0.8            2025 counts_averted  -1721.952611
                                1.0            2025 counts_averted  -2154.771535

draw                                                                    draw_991  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 2.296673
                                0.5            2025 pif                 5.637815
                                0.8            2025 pif                 8.857924
                                1.0            2025 pif                10.939392
            zero industry wheat 0.2            2025 pif                -0.362640
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  17629.029150
            zero industry wheat 0.2            2025 counts_averted   -295.648001
                                0.5            2025 counts_averted   -740.010467
                                0.8            2025 counts_averted  -1185.442294
                                1.0            2025 counts_averted  -1482.991379

draw                                                                    draw_992  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 4.922284
                                0.5            2025 pif                11.887513
                                0.8            2025 pif                18.376921
                                1.0            2025 pif                22.452918
            zero industry wheat 0.2            2025 pif                -0.800332
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  28666.348945
            zero industry wheat 0.2            2025 counts_averted   -478.478981
                                0.5            2025 counts_averted  -1199.178098
                                0.8            2025 counts_averted  -1923.460862
                                1.0            2025 counts_averted  -2408.310744

draw                                                                    draw_993  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 5.873616
                                0.5            2025 pif                14.134437
                                0.8            2025 pif                21.774810
                                1.0            2025 pif                26.544617
            zero industry wheat 0.2            2025 pif                -0.894605
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  37367.080352
            zero industry wheat 0.2            2025 counts_averted   -645.385664
                                0.5            2025 counts_averted  -1617.654703
                                0.8            2025 counts_averted  -2594.961428
                                1.0            2025 counts_averted  -3249.302936

draw                                                                    draw_994  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 1.460142
                                0.5            2025 pif                 3.613232
                                0.8            2025 pif                 5.722474
                                1.0            2025 pif                 7.104662
            zero industry wheat 0.2            2025 pif                -0.178520
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  18146.212257
            zero industry wheat 0.2            2025 counts_averted   -412.362789
                                0.5            2025 counts_averted  -1032.640512
                                0.8            2025 counts_averted  -1655.001332
                                1.0            2025 counts_averted  -2071.067401

draw                                                                    draw_995  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 3.052008
                                0.5            2025 pif                 7.453786
                                0.8            2025 pif                11.652171
                                1.0            2025 pif                14.342476
            zero industry wheat 0.2            2025 pif                -0.468075
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  21923.170766
            zero industry wheat 0.2            2025 counts_averted   -418.100877
                                0.5            2025 counts_averted  -1047.425880
                                0.8            2025 counts_averted  -1679.363631
                                1.0            2025 counts_averted  -2102.109381

draw                                                                    draw_996  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 9.037520
                                0.5            2025 pif                21.848935
                                0.8            2025 pif                33.813860
                                1.0            2025 pif                41.345610
            zero industry wheat 0.2            2025 pif                -1.536190
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  28061.048498
            zero industry wheat 0.2            2025 counts_averted   -623.913998
                                0.5            2025 counts_averted  -1565.176257
                                0.8            2025 counts_averted  -2512.927926
                                1.0            2025 counts_averted  -3148.378583

draw                                                                    draw_997  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 1.963255
                                0.5            2025 pif                 4.851136
                                0.8            2025 pif                 7.671830
                                1.0            2025 pif                 9.515635
            zero industry wheat 0.2            2025 pif                -0.245230
...                                                                          ...
522         industry wheat      1.0            2025 counts_averted  19970.525853
            zero industry wheat 0.2            2025 counts_averted   -439.603564
                                0.5            2025 counts_averted  -1101.246031
                                0.8            2025 counts_averted  -1765.577178
                                1.0            2025 counts_averted  -2209.960604

draw                                                                    draw_998  \
location_id vehicle             coverage_level year measure
6           industry wheat      0.2            2025 pif                 2.722935
                                0.5            2025 pif                 6.700742
                                0.8            2025 pif                10.553781

In [19]:
pd.read_pickle(iron_wra_results_path)

draw,location_id,vehicle,coverage_level,year,draw_0,draw_1,draw_10,draw_100,draw_101,draw_102,...,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999,measure
0,6,industry wheat,0.2,2025,8.747011,3.518091,4.393312,2.901456,8.394450,6.797294,...,4.226407,8.831263,11.072248,3.105137,5.736982,15.312890,4.131291,4.929218,4.243709,pif
1,6,industry wheat,0.5,2025,20.345378,8.565602,10.677052,7.097086,19.907517,16.143842,...,10.218129,20.741055,25.743565,7.596088,13.725292,36.152590,10.077140,11.975864,10.357611,pif
2,6,industry wheat,0.8,2025,30.329243,13.349182,16.610483,11.111338,30.232157,24.555267,...,15.814713,31.198536,38.354654,11.893664,21.026564,54.669131,15.733038,18.624580,16.180723,pif
3,6,industry wheat,1.0,2025,36.196233,16.397887,20.380706,13.690268,36.510926,29.687428,...,19.338220,37.443299,45.753047,14.654951,25.540590,65.843920,19.348729,22.846078,19.907337,pif
4,6,wheat flour,0.2,2025,4.415764,1.557727,2.435230,1.575256,5.744888,4.268582,...,2.660883,5.778444,6.448986,1.319826,3.416688,11.040773,1.809715,3.199169,2.478888,pif
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1591,522,zero maize flour,1.0,2025,-11.297324,-12.619286,-8.408191,-8.898661,-16.670311,-14.743523,...,-14.207221,-14.606813,-35.747149,-9.549296,-11.477650,-26.518527,-17.039902,-9.530199,-7.729041,rates_averted
1592,522,zero wheat flour,0.2,2025,-4.398975,-2.760898,-2.299612,-2.233432,-6.260540,-4.763208,...,-2.299051,-3.754986,-4.952415,-3.173237,-3.219026,-4.937540,-3.367979,-2.852288,-1.387054,rates_averted
1593,522,zero wheat flour,0.5,2025,-11.024389,-6.912180,-5.755421,-5.590129,-15.697636,-11.941140,...,-5.754329,-9.409889,-12.412343,-7.946034,-8.063724,-12.384614,-8.436600,-7.142323,-3.470032,rates_averted
1594,522,zero wheat flour,0.8,2025,-17.682209,-11.075398,-9.218905,-8.954693,-25.190364,-19.158893,...,-9.217656,-15.091755,-19.909908,-12.734380,-12.927847,-19.880753,-13.525232,-11.446297,-5.555889,rates_averted
1595,522,zero wheat flour,1.0,2025,-22.138796,-13.857516,-11.532159,-11.202110,-31.549804,-23.992893,...,-11.531016,-18.894673,-24.929230,-15.935261,-16.181403,-24.905521,-16.928789,-14.323365,-6.948060,rates_averted

In [60]:
ids_to_names('location')

location_id
1                                       Global
6                                        China
7        Democratic People's Republic of Korea
8                                       Taiwan
10                                    Cambodia
                         ...
95078                             Brazil North
95079                         Brazil Northeast
95080                      Brazil Central-West
95081                             Brazil South
95082                         Brazil Southeast
Name: location_name, Length: 70529, dtype: object

In [31]:
iron_bw_results_path = results_path / 'iron_bw_results.csv'
iron_bw_zero_results_path = results_path / 'iron_bw_results_zero_2021_04_14.csv'
iron_bw_industry_wheat_results_path = results_path / 'iron_bw_results_industry_wheat_2021_04_15.csv'

iron_u5_results_path = results_path / 'iron_u5.pkl'
iron_u5_industry_wheat_update_results_path = results_path / 'iron_u5_industry_wheat_update.pkl'
iron_wra_results_path = results_path / 'iron_wra.pkl'
iron_wra_industry_wheat_update_results_path = results_path / 'iron_wra_industry_wheat_update.pkl'

iron_maternal_disorders_wra_path = results_path / 'iron_maternal_disorders_wra.pkl'

folic_acid_results_path = results_path / 'folic_acid.pkl'
folic_acid_in_salt_results_path = results_path / 'folic_acid_in_salt.pkl'

zinc_results_path = results_path / 'zinc.pkl'
vitamin_a_oil_results_path = results_path / 'vitamin_a_oil_update.pkl'

# Load data, standardize format, and combine into single dataframe

In [61]:
%%time

def quadruplicate_draws(df):
    """Repeat each draw column in df 4 times to get all 1000 draws
    instead of only 250, filling in draw numbers based on which
    draws are missing.
    Assumes df has 250 arbitrarily chosen (e.g., random) draws
    between draw_0 and draw_999, as in iron_bw_results.csv,
    and returns a DataFrame in which all columns draw_0, ..., draw_999
    are present, but not necessarily in order.
    """
    draw_cols = df.filter(like='draw_').columns
    missing_draws = pd.Index(
        [f'draw_{n}' for n in range(1000)]).difference(draw_cols)
    draw_data = df[draw_cols]
    new_draw_data = pd.concat([draw_data] * 3, axis=1)
    new_draw_data.columns = missing_draws
    return pd.concat([df, new_draw_data], axis=1)

def draw_number_or_negative_one(columns):
    """Replaces column names of the form 'draw_X' with the integer X,
    and replaces other column names with -1. This is a vectorized key
    function to sort columns by putting all non-draw columns before
    draw columns, and sort draw columns numerically.
    """
    is_draw = columns.str.fullmatch(r'draw_\d{1,3}')
    column_sort_keys = np.where(is_draw, columns.str[5:], -1).astype(int)
    return column_sort_keys

iron_bw_results = (
    pd.concat([
        pd.read_csv(iron_bw_results_path),
        pd.read_csv(iron_bw_zero_results_path),
        pd.read_csv(iron_bw_industry_wheat_results_path),
    ], ignore_index=True)
    .pipe(quadruplicate_draws)
    .assign(year=2025, nutrient='iron', age_group='u5',
            cause='low_birthweight',
            location=lambda df: df['location_id'].map(ids_to_names('location')),
           )
)

iron_anemia_u5_results = (
    pd.concat([
        pd.read_pickle(iron_u5_results_path),
        pd.read_pickle(iron_u5_industry_wheat_update_results_path),
    ], ignore_index=True)
    # Replace the original industry wheat results with "industry wheat update" results
    .drop_duplicates(
        ['vehicle', 'coverage_level', 'location_id', 'year', 'measure'],
        keep='last',
        ignore_index=True,
    )
    .assign(nutrient='iron', age_group='u5', cause='anemia',
            location=lambda df: df['location_id'].map(ids_to_names('location')),
           )
)

iron_anemia_wra_results = (
    pd.concat([
        pd.read_pickle(iron_wra_results_path),
        pd.read_pickle(iron_wra_industry_wheat_update_results_path),
    ], ignore_index=True)
    # Replace the original industry wheat results with "industry wheat update" results
    .drop_duplicates(
        ['vehicle', 'coverage_level', 'location_id', 'year', 'measure'],
        keep='last',
        ignore_index=True,
    )
    .assign(nutrient='iron', age_group='wra', cause='anemia',
            location=lambda df: df['location_id'].map(ids_to_names('location')),
           )
)

iron_maternal_disorders_results = (
    pd.read_pickle(iron_maternal_disorders_wra_path)
    .reset_index()
    .assign(year=lambda df: df['year'].astype(int))
    .assign(nutrient='iron', age_group='wra', cause='maternal_disorders',
           location=lambda df: df['location_id'].map(ids_to_names('location')),
           )
)

folic_acid_results = (
    pd.concat([
        pd.read_pickle(folic_acid_results_path),
        pd.read_pickle(
            folic_acid_in_salt_results_path
        ).assign(nutrient='folic acid', vehicle='salt'),
    ], ignore_index=True)
    .rename(columns={'year_id': 'year'})
    .assign(age_group='u5', cause='neural_tube_defects',
           location=lambda df: df['location_id'].map(ids_to_names('location')),
           )
)

zinc_results = (
    pd.read_pickle(zinc_results_path)
    .assign(nutrient='zinc', age_group='u5', cause='diarrheal_diseases',
           location=lambda df: df['location_id'].map(ids_to_names('location')),
           )
)

vitamin_a_oil_results = (
    pd.read_pickle(vitamin_a_oil_results_path)
    .assign(nutrient = 'vitamin a', age_group='u5',
            cause='vad|dd|measles',
           location=lambda df: df['location_id'].map(ids_to_names('location')),
           )
)

# Combine all results in to one DataFrame - columns will be sorted
# according to the column order of the first df in the list
results = pd.concat([
    # Sort columns of first dataframe to concat so others
    # will be automatically aligned
    iron_bw_results.sort_index(axis=1, key=draw_number_or_negative_one),
    iron_anemia_u5_results,
    iron_anemia_wra_results,
    iron_maternal_disorders_results,
    folic_acid_results,
    zinc_results,
    vitamin_a_oil_results
], ignore_index=True)

results

CPU times: user 722 ms, sys: 161 ms, total: 883 ms
Wall time: 898 ms

,coverage_level,location_id,location,cause,vehicle,measure,nutrient,year,age_group,draw_0,...,draw_990,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999
0,0.2,6,China,low_birthweight,wheat flour,counts_averted,iron,2025,u5,2904.543372,...,4450.653495,3373.314205,2202.609063,3980.202743,1817.149521,1443.065174,2202.609063,1817.149521,3654.702138,3654.702138
1,0.2,11,Indonesia,low_birthweight,wheat flour,counts_averted,iron,2025,u5,0.410664,...,55.307435,68.835866,318.490189,36.359475,87.106196,130.843194,318.490189,87.106196,30.681769,30.681769
2,0.2,15,Myanmar,low_birthweight,wheat flour,counts_averted,iron,2025,u5,22.630438,...,75.879004,24.705208,51.528323,29.401829,10.900119,44.477208,51.528323,10.900119,84.762431,84.762431
3,0.2,20,Viet Nam,low_birthweight,wheat flour,counts_averted,iron,2025,u5,40.655603,...,98.195414,33.785295,30.470178,13.679045,24.439117,21.388484,30.470178,24.439117,36.171505,36.171505
4,0.2,141,Egypt,low_birthweight,maize flour,counts_averted,iron,2025,u5,366.596716,...,1083.183300,892.482109,458.504144,384.333877,454.108400,923.678018,458.504144,454.108400,385.494035,385.494035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20872,1.0,522,Sudan,vad|dd|measles,zero industry oil,rates_averted,vitamin a,2025,u5,-280.528083,...,-100.707815,-120.156925,-432.523437,-446.087736,-199.101797,-156.058629,-156.080886,-132.122548,-127.778290,-57.591651
20873,0.2,522,Sudan,vad|dd|measles,zero oil,rates_averted,vitamin a,2025,u5,-56.105617,...,-20.141563,-24.031385,-86.504687,-89.217547,-39.820359,-31.211726,-31.216177,-26.424510,-25.555658,-11.518330
20874,0.5,522,Sudan,vad|dd|measles,zero oil,rates_averted,vitamin a,2025,u5,-140.264041,...,-50.353908,-60.078463,-216.261718,-223.043868,-99.550899,-78.029315,-78.040443,-66.061274,-63.889145,-28.795826
20875,0.8,522,Sudan,vad|dd|measles,zero oil,rates_averted,vitamin a,2025,u5,-224.422466,...,-80.566252,-96.125540,-346.018749,-356.870189,-159.281438,-124.846903,-124.864709,-105.698039,-102.222632,-46.073321
20876,1.0,522,Sudan,vad|dd|measles,zero oil,rates_averted,vitamin a,2025,u5,-280.528083,...,-100.707815,-120.156925,-432.523437,-446.087736,-199.101797,-156.058629,-156.080886,-132.122548,-127.778290,-57.591651

# Check number of deduplicated rows

Make sure we dropped the correct number of rows when replacing "industry wheat" results with the updated values.

Yep, looks good.

In [45]:
# Number of dropped rows = original total - deduplicated total
22077 - 20877

1200

In [44]:
# (original - deduplicated) / # locations / # coverage levels / # measures / # vehicles / # age groups / # years
# (22077 - 20877) / 25 locations / #{0.2, 0.5, 0.8, 1.0} / #{counts_averted, rates_averted, pif}
#     / #{industry wheat, zero industry wheat} / #{u5, wra} / #{2025}
#     = 1 dropped row per combination of these 6 variables
(22077 - 20877) / 25 / 4 / 3 / 2 / 2 / 1

1.0

# Define draw columns and non-draw columns

In [63]:
draw_cols = results.filter(like='draw').columns
non_draw_cols = results.columns.difference(draw_cols)
print(len(draw_cols))
non_draw_cols

1000

Index(['age_group', 'cause', 'coverage_level', 'location', 'location_id',
       'measure', 'nutrient', 'vehicle', 'year'],
      dtype='object')

# View all interventions

In [64]:
def get_interventions(results):
    all_interventions = results.groupby(['age_group', 'vehicle', 'nutrient', 'cause'])['coverage_level'].unique()
    return all_interventions

all_interventions = get_interventions(results)
all_interventions

age_group  vehicle              nutrient    cause
u5         industry oil         vitamin a   vad|dd|measles         [0.2, 0.5, 0.8, 1.0]
           industry wheat       iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            low_birthweight             [0.2, 0.5, 0.8]
                                zinc        diarrheal_diseases     [0.2, 0.5, 0.8, 1.0]
           maize flour          folic acid  neural_tube_defects         [0.2, 0.5, 0.8]
                                iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            low_birthweight             [0.2, 0.5, 0.8]
                                zinc        diarrheal_diseases     [0.2, 0.5, 0.8, 1.0]
           oil                  vitamin a   vad|dd|measles         [0.2, 0.5, 0.8, 1.0]
           salt                 folic acid  neural_tube_defects         [0.2, 0.5, 0.8]
           wheat flour          folic acid  neural_tube_defects         [0.2, 0.5, 0.8]
                                iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            low_birthweight             [0.2, 0.5, 0.8]
                                zinc        diarrheal_diseases     [0.2, 0.5, 0.8, 1.0]
           zero industry oil    vitamin a   vad|dd|measles         [0.2, 0.5, 0.8, 1.0]
           zero industry wheat  iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                zinc        diarrheal_diseases     [0.2, 0.5, 0.8, 1.0]
           zero maize flour     iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            low_birthweight                       [nan]
                                zinc        diarrheal_diseases     [0.2, 0.5, 0.8, 1.0]
           zero oil             vitamin a   vad|dd|measles         [0.2, 0.5, 0.8, 1.0]
           zero wheat flour     iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            low_birthweight                       [nan]
                                zinc        diarrheal_diseases     [0.2, 0.5, 0.8, 1.0]
wra        industry wheat       iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            maternal_disorders     [0.2, 0.5, 0.8, 1.0]
           maize flour          iron        anemia                 [0.2, 0.5, 0.8, 1.0]
           wheat flour          iron        anemia                 [0.2, 0.5, 0.8, 1.0]
           zero industry wheat  iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            maternal_disorders     [0.2, 0.5, 0.8, 1.0]
           zero maize flour     iron        anemia                 [0.2, 0.5, 0.8, 1.0]
           zero wheat flour     iron        anemia                 [0.2, 0.5, 0.8, 1.0]
Name: coverage_level, dtype: object

# Get IDs for the three locations we're interested in

In [8]:
location_ids = names_to_ids('location', 'Nigeria', 'Ethiopia', 'India')
location_ids

location_name
India       163
Ethiopia    179
Nigeria     214
Name: location_id, dtype: int64

In [9]:
nigeria_results = results.query(f"location_id == {location_ids['Nigeria']}")
nigeria_results

,coverage_level,location_id,measure,vehicle,year,nutrient,age_group,cause,draw_0,draw_1,...,draw_990,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999
38,0.2,214,counts_averted,maize flour,2025,iron,u5,low_birthweight,4168.286078,5304.212521,...,6266.221575,3301.583392,3065.940881,3607.754906,2105.639178,2348.115348,3065.940881,2105.639178,3907.238560,3907.238560
39,0.2,214,counts_averted,wheat flour,2025,iron,u5,low_birthweight,11717.773503,25761.069875,...,23162.904985,8738.507403,8899.548655,12801.686674,9074.032780,15879.512296,8899.548655,9074.032780,11599.017060,11599.017060
80,0.5,214,counts_averted,maize flour,2025,iron,u5,low_birthweight,5241.374957,6661.305570,...,7701.095110,4002.401676,3829.767784,4353.235512,2602.084114,2940.870447,3829.767784,2602.084114,4676.036904,4676.036904
81,0.5,214,counts_averted,wheat flour,2025,iron,u5,low_birthweight,14730.712383,32395.235089,...,28835.722080,10879.998736,11085.883263,16131.508600,11443.733674,19697.793129,11085.883263,11443.733674,14431.721110,14431.721110
122,0.8,214,counts_averted,maize flour,2025,iron,u5,low_birthweight,5995.460317,7603.293178,...,9117.143635,4860.512872,4514.993679,5269.234032,3148.974934,3595.396197,4514.993679,3148.974934,5495.166076,5495.166076
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21992,1.0,214,rates_averted,zero industry oil,2025,vitamin a,u5,vad|dd|measles,-34.058031,-36.794145,...,-9.889892,-18.382523,-46.263812,-28.042192,-24.979701,-13.720283,-13.292790,-17.176543,-15.830062,-5.856377
21993,0.2,214,rates_averted,zero oil,2025,vitamin a,u5,vad|dd|measles,-6.811606,-7.358829,...,-1.977978,-3.676505,-9.252762,-5.608438,-4.995940,-2.744057,-2.658558,-3.435309,-3.166012,-1.171275
21994,0.5,214,rates_averted,zero oil,2025,vitamin a,u5,vad|dd|measles,-17.029015,-18.397073,...,-4.944946,-9.191262,-23.131906,-14.021096,-12.489851,-6.860142,-6.646395,-8.588271,-7.915031,-2.928189
21995,0.8,214,rates_averted,zero oil,2025,vitamin a,u5,vad|dd|measles,-27.246425,-29.435316,...,-7.911914,-14.706019,-37.011050,-22.433754,-19.983761,-10.976226,-10.634232,-13.741234,-12.664050,-4.685102
21996,1.0,214,rates_averted,zero oil,2025,vitamin a,u5,vad|dd|measles,-34.058031,-36.794145,...,-9.889892,-18.382523,-46.263812,-28.042192,-24.979701,-13.720283,-13.292790,-17.176543,-15.830062,-5.856377

In [10]:
get_interventions(nigeria_results.query("nutrient in ['iron', 'folic acid']"))

age_group  vehicle              nutrient    cause
u5         industry wheat       iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            low_birthweight             [0.2, 0.5, 0.8]
           maize flour          folic acid  neural_tube_defects         [0.2, 0.5, 0.8]
                                iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            low_birthweight             [0.2, 0.5, 0.8]
           salt                 folic acid  neural_tube_defects         [0.2, 0.5, 0.8]
           wheat flour          folic acid  neural_tube_defects         [0.2, 0.5, 0.8]
                                iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            low_birthweight             [0.2, 0.5, 0.8]
           zero industry wheat  iron        anemia                 [0.2, 0.5, 0.8, 1.0]
           zero maize flour     iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            low_birthweight                       [nan]
           zero wheat flour     iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            low_birthweight                       [nan]
wra        industry wheat       iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            maternal_disorders     [0.2, 0.5, 0.8, 1.0]
           maize flour          iron        anemia                 [0.2, 0.5, 0.8, 1.0]
           wheat flour          iron        anemia                 [0.2, 0.5, 0.8, 1.0]
           zero industry wheat  iron        anemia                 [0.2, 0.5, 0.8, 1.0]
                                            maternal_disorders     [0.2, 0.5, 0.8, 1.0]
           zero maize flour     iron        anemia                 [0.2, 0.5, 0.8, 1.0]
           zero wheat flour     iron        anemia                 [0.2, 0.5, 0.8, 1.0]
Name: coverage_level, dtype: object

In [113]:
6

6

In [76]:
non_draw_cols.difference(['vehicle'])

Index(['age_group', 'cause', 'coverage_level', 'location', 'location_id',
       'measure', 'nutrient', 'year'],
      dtype='object')

In [114]:
filters = [
    # f"location_id == {location_ids['India']}",
    f"location_id in {location_ids.to_list()}", 
    "nutrient in ['iron', 'folic acid']",
    "coverage_level == 0.8",
    "year == 2025",
    # "measure == 'rates_averted'",
    "measure == 'pif'",
    "not vehicle.str.contains('zero')",
    # "not vehicle.str.contains('maize')",
]

query_string = " and ".join(filters)

def lower(x):
    return x.quantile(.025)

def upper(x):
    return x.quantile(0.975)

t = (
    results
    .query(query_string)
    .set_index(non_draw_cols.to_list())
    [draw_cols]
    .agg(['mean', lower, upper], axis=1)
    .groupby(non_draw_cols.difference(['vehicle']).to_list()).max()
    # .mean()
    # .count()
    .sort_index(level=['measure', 'location'])
    .reorder_levels(['coverage_level', 'year',  'measure', 'location_id', 'location', 'age_group', 'nutrient', 'cause'])
)
t

                                                                                                mean  \
coverage_level year measure location_id location age_group nutrient   cause
0.8            2025 pif     179         Ethiopia u5        iron       anemia                3.671648
                                                                      low_birthweight       0.108529
                                                           folic acid neural_tube_defects  19.643150
                                                 wra       iron       anemia                7.156713
                                                                      maternal_disorders    4.214878
                            163         India    u5        iron       anemia                2.803583
                                                                      low_birthweight       0.119496
                                                           folic acid neural_tube_defects  21.604038
                                                 wra       iron       anemia                3.860289
                                                                      maternal_disorders    3.947502
                            214         Nigeria  u5        iron       anemia                6.577747
                                                                      low_birthweight       0.147102
                                                           folic acid neural_tube_defects  18.372480
                                                 wra       iron       anemia               13.385730
                                                                      maternal_disorders    9.327002

                                                                                               lower  \
coverage_level year measure location_id location age_group nutrient   cause
0.8            2025 pif     179         Ethiopia u5        iron       anemia                0.041564
                                                                      low_birthweight       0.040176
                                                           folic acid neural_tube_defects  14.392610
                                                 wra       iron       anemia                0.071016
                                                                      maternal_disorders    0.036190
                            163         India    u5        iron       anemia                0.031211
                                                                      low_birthweight       0.043072
                                                           folic acid neural_tube_defects  16.160131
                                                 wra       iron       anemia                0.043067
                                                                      maternal_disorders    0.040148
                            214         Nigeria  u5        iron       anemia                0.072341
                                                                      low_birthweight       0.058567
                                                           folic acid neural_tube_defects  13.256967
                                                 wra       iron       anemia                0.156626
                                                                      maternal_disorders    0.116341

                                                                                               upper
coverage_level year measure location_id location age_group nutrient   cause
0.8            2025 pif     179         Ethiopia u5        iron       anemia                9.099812
                                                                      low_birthweight       0.314603
                                                           folic acid neural_tube_defects  24.657746
                                                 wra       iron       anemia               17.521088
                                                                      maternal_disorders    9.326217
                            163         India    u5        iron       anemia                6.569159
                                                                      low_birthweight       0.233562
                                                           folic acid neural_tube_defects  26.565498
                                                 wra       iron       anemia                8.965414
                                                                      maternal_disorders    8.935087
                            214         Nigeria  u5        iron       anemia               15.635443
                                                                      low_birthweight       0.247283
                                                           folic acid neural_tube_defects  24.056251
                                                 wra       iron       anemia               31.796247
                                                                      maternal_disorders   21.354283

In [115]:
filename = "maximum_pifs_by_pathway.csv"
t.to_csv(filename)
pd.read_csv(filename)

,coverage_level,year,measure,location_id,location,age_group,nutrient,cause,mean,lower,upper
0,0.8,2025,pif,179,Ethiopia,u5,iron,anemia,3.671648,0.041564,9.099812
1,0.8,2025,pif,179,Ethiopia,u5,iron,low_birthweight,0.108529,0.040176,0.314603
2,0.8,2025,pif,179,Ethiopia,u5,folic acid,neural_tube_defects,19.643150,14.392610,24.657746
3,0.8,2025,pif,179,Ethiopia,wra,iron,anemia,7.156713,0.071016,17.521088
4,0.8,2025,pif,179,Ethiopia,wra,iron,maternal_disorders,4.214878,0.036190,9.326217
5,0.8,2025,pif,163,India,u5,iron,anemia,2.803583,0.031211,6.569159
6,0.8,2025,pif,163,India,u5,iron,low_birthweight,0.119496,0.043072,0.233562
7,0.8,2025,pif,163,India,u5,folic acid,neural_tube_defects,21.604038,16.160131,26.565498
8,0.8,2025,pif,163,India,wra,iron,anemia,3.860289,0.043067,8.965414
9,0.8,2025,pif,163,India,wra,iron,maternal_disorders,3.947502,0.040148,8.935087
10,0.8,2025,pif,214,Nigeria,u5,iron,anemia,6.577747,0.072341,15.635443
11,0.8,2025,pif,214,Nigeria,u5,iron,low_birthweight,0.147102,0.058567,0.247283
12,0.8,2025,pif,214,Nigeria,u5,folic acid,neural_tube_defects,18.372480,13.256967,24.056251
13,0.8,2025,pif,214,Nigeria,wra,iron,anemia,13.385730,0.156626,31.796247
14,0.8,2025,pif,214,Nigeria,wra,iron,maternal_disorders,9.327002,0.116341,21.354283

In [100]:
t1=t
t1

                                                                                                           mean  \
coverage_level year measure        location_id location age_group nutrient   cause
0.8            2025 counts_averted 179         Ethiopia u5        iron       anemia                10315.781259
                                                                             low_birthweight        6622.302302
                                                                  folic acid neural_tube_defects   50471.080161
                                                        wra       iron       anemia                10265.551338
                                                                             maternal_disorders      765.318570
                                   163         India    u5        iron       anemia                50580.043697
                                                                             low_birthweight       47576.280327
                                                                  folic acid neural_tube_defects  151654.381344
                                                        wra       iron       anemia               252133.197437
                                                                             maternal_disorders     9440.221952
                                   214         Nigeria  u5        iron       anemia                44557.683534
                                                                             low_birthweight       26232.641277
                                                                  folic acid neural_tube_defects  264739.868256
                                                        wra       iron       anemia                95130.526197
                                                                             maternal_disorders     7472.655988

                                                                                                          lower  \
coverage_level year measure        location_id location age_group nutrient   cause
0.8            2025 counts_averted 179         Ethiopia u5        iron       anemia                  104.838348
                                                                             low_birthweight        2021.387730
                                                                  folic acid neural_tube_defects   28089.104226
                                                        wra       iron       anemia                   99.047958
                                                                             maternal_disorders        5.221821
                                   163         India    u5        iron       anemia                  523.581537
                                                                             low_birthweight       16406.606236
                                                                  folic acid neural_tube_defects   76041.793123
                                                        wra       iron       anemia                 2644.336360
                                                                             maternal_disorders       62.377279
                                   214         Nigeria  u5        iron       anemia                  535.188701
                                                                             low_birthweight       10237.225097
                                                                  folic acid neural_tube_defects  127066.626513
                                                        wra       iron       anemia                 1170.356946
                                                                             maternal_disorders       47.890382

                                                                                                          upper
coverage_level year measure        location_id location age_group nutrient   cause
0.8            2025 counts_averted 179         Ethiopia u5        iron       anemia                21094.441110
                                                                             low_birthweight       11819.968694
                                                                  folic acid neural_tube_defects   81081.125482
                                                        wra       iron       anemia                21428.691613
                                                                             maternal_disorders     2152.778693
                                   163         India    u5        iron       anemia               113768.382997
                                                                             low_birthweight       97190.398148
                                                                  folic acid neural_tube_defects  274038.436051
                                                        wra       iron       anemia               561844.607737
                                                                             maternal_disorders    24523.913075
                                   214         Nigeria  u5        iron       anemia               102242.796055
                                                                             low_birthweight       45584.005664
                                                                  folic acid neural_tube_defects  508731.885696
                                                        wra       iron       anemia               215747.181791
                                                                             maternal_disorders    21852.976052

In [102]:
t1.compare(t)

                                                                                                    mean  \
                                                                                                    self
coverage_level year measure        location_id location age_group nutrient cause
0.8            2025 counts_averted 179         Ethiopia u5        iron     anemia                    NaN
                                                                           low_birthweight           NaN
                                                        wra       iron     anemia           10265.551338

                                                                                                          \
                                                                                                   other
coverage_level year measure        location_id location age_group nutrient cause
0.8            2025 counts_averted 179         Ethiopia u5        iron     anemia                    NaN
                                                                           low_birthweight           NaN
                                                        wra       iron     anemia           13572.831869

                                                                                                lower  \
                                                                                                 self
coverage_level year measure        location_id location age_group nutrient cause
0.8            2025 counts_averted 179         Ethiopia u5        iron     anemia                 NaN
                                                                           low_birthweight        NaN
                                                        wra       iron     anemia           99.047958

                                                                                                        \
                                                                                                 other
coverage_level year measure        location_id location age_group nutrient cause
0.8            2025 counts_averted 179         Ethiopia u5        iron     anemia                  NaN
                                                                           low_birthweight         NaN
                                                        wra       iron     anemia           118.050729

                                                                                                   upper  \
                                                                                                    self
coverage_level year measure        location_id location age_group nutrient cause
0.8            2025 counts_averted 179         Ethiopia u5        iron     anemia           21094.441110
                                                                           low_birthweight  11819.968694
                                                        wra       iron     anemia           21428.691613


                                                                                                   other
coverage_level year measure        location_id location age_group nutrient cause
0.8            2025 counts_averted 179         Ethiopia u5        iron     anemia           23648.495249
                                                                           low_birthweight  18440.698719
                                                        wra       iron     anemia           31234.645766

In [90]:
t1.compare(t)

                                                                                                mean  \
                                                                                                self
coverage_level year measure       location_id location age_group nutrient cause
0.8            2025 rates_averted 179         Ethiopia u5        iron     anemia                 NaN
                                                                          low_birthweight        NaN
                                                       wra       iron     anemia           39.306423

                                                                                                     \
                                                                                              other
coverage_level year measure       location_id location age_group nutrient cause
0.8            2025 rates_averted 179         Ethiopia u5        iron     anemia                NaN
                                                                          low_birthweight       NaN
                                                       wra       iron     anemia           29.72866

                                                                                              lower  \
                                                                                               self
coverage_level year measure       location_id location age_group nutrient cause
0.8            2025 rates_averted 179         Ethiopia u5        iron     anemia                NaN
                                                                          low_birthweight       NaN
                                                       wra       iron     anemia           0.341871

                                                                                                     \
                                                                                              other
coverage_level year measure       location_id location age_group nutrient cause
0.8            2025 rates_averted 179         Ethiopia u5        iron     anemia                NaN
                                                                          low_birthweight       NaN
                                                       wra       iron     anemia           0.286839

                                                                                                upper  \
                                                                                                 self
coverage_level year measure       location_id location age_group nutrient cause
0.8            2025 rates_averted 179         Ethiopia u5        iron     anemia           141.780355
                                                                          low_birthweight  113.625002
                                                       wra       iron     anemia            90.454388


                                                                                                other
coverage_level year measure       location_id location age_group nutrient cause
0.8            2025 rates_averted 179         Ethiopia u5        iron     anemia           126.467977
                                                                          low_birthweight   73.605835
                                                       wra       iron     anemia            62.056705

In [79]:
t.groupby(non_draw_cols.difference(['vehicle']).to_list()).max()

                                                                                                           mean  \
age_group cause               coverage_level location location_id measure        nutrient   year
u5        anemia              0.8            Ethiopia 179         counts_averted iron       2025   10315.781259
                                             India    163         counts_averted iron       2025   50580.043697
                                             Nigeria  214         counts_averted iron       2025   44557.683534
          low_birthweight     0.8            Ethiopia 179         counts_averted iron       2025    6622.302302
                                             India    163         counts_averted iron       2025   47576.280327
                                             Nigeria  214         counts_averted iron       2025   26232.641277
          neural_tube_defects 0.8            Ethiopia 179         counts_averted folic acid 2025   50471.080161
                                             India    163         counts_averted folic acid 2025  151654.381344
                                             Nigeria  214         counts_averted folic acid 2025  264739.868256
wra       anemia              0.8            Ethiopia 179         counts_averted iron       2025   10265.551338
                                             India    163         counts_averted iron       2025  252133.197437
                                             Nigeria  214         counts_averted iron       2025   95130.526197
          maternal_disorders  0.8            Ethiopia 179         counts_averted iron       2025     765.318570
                                             India    163         counts_averted iron       2025    9440.221952
                                             Nigeria  214         counts_averted iron       2025    7472.655988

                                                                                                          lower  \
age_group cause               coverage_level location location_id measure        nutrient   year
u5        anemia              0.8            Ethiopia 179         counts_averted iron       2025     104.838348
                                             India    163         counts_averted iron       2025     523.581537
                                             Nigeria  214         counts_averted iron       2025     535.188701
          low_birthweight     0.8            Ethiopia 179         counts_averted iron       2025    2021.387730
                                             India    163         counts_averted iron       2025   16406.606236
                                             Nigeria  214         counts_averted iron       2025   10237.225097
          neural_tube_defects 0.8            Ethiopia 179         counts_averted folic acid 2025   28089.104226
                                             India    163         counts_averted folic acid 2025   76041.793123
                                             Nigeria  214         counts_averted folic acid 2025  127066.626513
wra       anemia              0.8            Ethiopia 179         counts_averted iron       2025      99.047958
                                             India    163         counts_averted iron       2025    2644.336360
                                             Nigeria  214         counts_averted iron       2025    1170.356946
          maternal_disorders  0.8            Ethiopia 179         counts_averted iron       2025       5.221821
                                             India    163         counts_averted iron       2025      62.377279
                                             Nigeria  214         counts_averted iron       2025      47.890382

                                                                                                          upper
age_group cause               coverage_level location location_id measure        nutrient   year
u5        anemia              0.8            Ethiopia 179         counts_averted iron       2025   21094.441110
                                             India    163         counts_averted iron       2025  113768.382997
                                             Nigeria  214         counts_averted iron       2025  102242.796055
          low_birthweight     0.8            Ethiopia 179         counts_averted iron       2025   11819.968694
                                             India    163         counts_averted iron       2025   97190.398148
                                             Nigeria  214         counts_averted iron       2025   45584.005664
          neural_tube_defects 0.8            Ethiopia 179         counts_averted folic acid 2025   81081.125482
                                             India    163         counts_averted folic acid 2025  274038.436051
                                             Nigeria  214         counts_averted folic acid 2025  508731.885696
wra       anemia              0.8            Ethiopia 179         counts_averted iron       2025   21428.691613
                                             India    163         counts_averted iron       2025  561844.607737
                                             Nigeria  214         counts_averted iron       2025  215747.181791
          maternal_disorders  0.8            Ethiopia 179         counts_averted iron       2025    2152.778693
                                             India    163         counts_averted iron       2025   24523.913075
                                             Nigeria  214         counts_averted iron       2025   21852.976052

In [47]:
t.groupby(list(non_draw_cols)).count()

                                                                                                        mean  \
age_group cause               coverage_level location_id measure        nutrient   vehicle        year
u5        anemia              0.5            214         counts_averted iron       industry wheat 2025     1
                                                                                   maize flour    2025     1
                                                                                   wheat flour    2025     1
          low_birthweight     0.5            214         counts_averted iron       industry wheat 2025     1
                                                                                   maize flour    2025     1
                                                                                   wheat flour    2025     1
          neural_tube_defects 0.5            214         counts_averted folic acid maize flour    2025     1
                                                                                   salt           2025     1
                                                                                   wheat flour    2025     1
wra       anemia              0.5            214         counts_averted iron       industry wheat 2025     1
                                                                                   maize flour    2025     1
                                                                                   wheat flour    2025     1
          maternal_disorders  0.5            214         counts_averted iron       industry wheat 2025     1

                                                                                                        lower  \
age_group cause               coverage_level location_id measure        nutrient   vehicle        year
u5        anemia              0.5            214         counts_averted iron       industry wheat 2025      1
                                                                                   maize flour    2025      1
                                                                                   wheat flour    2025      1
          low_birthweight     0.5            214         counts_averted iron       industry wheat 2025      1
                                                                                   maize flour    2025      1
                                                                                   wheat flour    2025      1
          neural_tube_defects 0.5            214         counts_averted folic acid maize flour    2025      1
                                                                                   salt           2025      1
                                                                                   wheat flour    2025      1
wra       anemia              0.5            214         counts_averted iron       industry wheat 2025      1
                                                                                   maize flour    2025      1
                                                                                   wheat flour    2025      1
          maternal_disorders  0.5            214         counts_averted iron       industry wheat 2025      1

                                                                                                        upper
age_group cause               coverage_level location_id measure        nutrient   vehicle        year
u5        anemia              0.5            214         counts_averted iron       industry wheat 2025      1
                                                                                   maize flour    2025      1
                                                                                   wheat flour    2025      1
          low_birthweight     0.5            214         counts_averted iron       industry wheat 2025      1
                                                                                   maize flour    2025      1
                                                                                   wheat flour    2025      1
          neural_tube_defects 0.5            214         counts_averted folic acid maize flour    2025      1
                                                                                   salt           2025      1
                                                                                   wheat flour    2025      1
wra       anemia              0.5            214         counts_averted iron       industry wheat 2025      1
                                                                                   maize flour    2025      1
                                                                                   wheat flour    2025      1
          maternal_disorders  0.5            214         counts_averted iron       industry wheat 2025      1

In [58]:
non_draw_cols.to_list()

['age_group',
 'cause',
 'coverage_level',
 'location_id',
 'measure',
 'nutrient',
 'vehicle',
 'year']

In [12]:
iron_anemia_u5_industry = iron_anemia_u5_results.query("vehicle.str.contains('industry')")
iron_anemia_u5_industry

draw,location_id,coverage_level,year,vehicle,draw_0,draw_1,draw_10,draw_100,draw_101,draw_102,...,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999,measure,nutrient,age_group,cause
0,6,0.2,2025,industry wheat,6.394933,2.343036,3.264021,1.889394,6.099295,5.016220,...,2.277403,4.335902,11.760010,3.233146,3.712411,3.475743,pif,iron,u5,anemia
1,6,0.5,2025,industry wheat,14.975322,5.708617,7.939372,4.632439,14.489039,11.959095,...,5.571873,10.421399,27.831902,7.899147,9.001633,8.492461,pif,iron,u5,anemia
2,6,0.8,2025,industry wheat,22.484278,8.904114,12.363614,7.270039,22.053413,18.262833,...,8.726392,16.040117,42.217856,12.353355,13.975274,13.282175,pif,iron,u5,anemia
3,6,1.0,2025,industry wheat,26.966619,10.944587,15.180889,8.971922,26.681654,22.140738,...,10.754880,19.545161,50.970627,15.209854,17.126090,16.354219,pif,iron,u5,anemia
8,6,0.2,2025,zero industry wheat,-0.444387,-0.140759,-0.246195,-0.139023,-0.576749,-0.433155,...,-0.131144,-0.353225,-1.175903,-0.191889,-0.329320,-0.275872,pif,iron,u5,anemia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2191,522,1.0,2025,industry wheat,257.005440,137.978019,118.841408,111.666940,242.552024,236.646736,...,146.792945,197.258925,267.463796,171.493759,123.774497,101.862440,rates_averted,iron,u5,anemia
2192,522,0.2,2025,zero industry wheat,-4.164923,-2.639730,-2.066579,-2.200436,-5.487101,-4.803434,...,-3.297371,-3.650168,-5.689624,-3.683392,-2.547710,-1.430041,rates_averted,iron,u5,anemia
2193,522,0.5,2025,zero industry wheat,-10.432208,-6.607059,-5.170541,-5.505601,-13.749180,-12.030521,...,-8.254199,-9.137238,-14.254726,-9.220370,-6.377359,-3.576869,rates_averted,iron,u5,anemia
2194,522,0.8,2025,zero industry wheat,-16.723388,-10.583670,-8.279414,-8.816180,-22.048993,-19.283938,...,-13.223954,-14.638492,-22.856634,-14.771614,-10.216715,-5.725816,rates_averted,iron,u5,anemia
2195,522,1.0,2025,zero industry wheat,-20.930791,-13.239901,-10.354725,-11.026241,-27.603176,-24.134181,...,-16.544308,-18.313874,-28.611689,-18.480367,-12.781680,-7.159624,rates_averted,iron,u5,anemia

In [20]:
x = pd.read_pickle(iron_u5_industry_wheat_results_path)
x

draw,location_id,coverage_level,year,vehicle,draw_0,draw_1,draw_10,draw_100,draw_101,draw_102,...,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999,measure
0,6,0.2,2025,industry wheat,3.214088,1.118524,1.684095,0.965343,3.480620,2.737738,...,1.596346,3.621688,4.199178,1.072679,2.307565,6.923879,1.537115,2.053347,1.829435,pif
1,6,0.5,2025,industry wheat,7.777186,2.762206,4.151225,2.389536,8.452598,6.670246,...,3.923702,8.719056,10.117121,2.654606,5.649876,16.761471,3.801178,5.047455,4.518938,pif
2,6,0.8,2025,industry wheat,12.048928,4.365913,6.549429,3.785649,13.141853,10.403356,...,6.173010,13.442606,15.608101,4.204651,8.854652,25.981634,6.016235,7.941823,7.144208,pif
3,6,1.0,2025,industry wheat,14.744571,5.413359,8.110969,4.701071,16.119469,12.786432,...,7.630569,16.398815,19.047411,5.220647,10.917632,31.806669,7.466224,9.817803,8.859441,pif
4,6,0.2,2025,zero industry wheat,-0.444387,-0.140759,-0.246195,-0.139023,-0.576749,-0.433155,...,-0.251820,-0.590484,-0.639088,-0.131144,-0.353225,-1.175903,-0.191889,-0.329320,-0.275872,pif
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,522,1.0,2025,industry wheat,257.005440,137.978019,118.841408,111.666940,242.552024,236.646736,...,117.002905,260.784254,308.463213,146.792945,197.258925,267.463796,171.493759,123.774497,101.862440,rates_averted
596,522,0.2,2025,zero industry wheat,-4.164923,-2.639730,-2.066579,-2.200436,-5.487101,-4.803434,...,-1.935714,-4.176262,-5.166152,-3.297371,-3.650168,-5.689624,-3.683392,-2.547710,-1.430041,rates_averted
597,522,0.5,2025,zero industry wheat,-10.432208,-6.607059,-5.170541,-5.505601,-13.749180,-12.030521,...,-4.843584,-10.457141,-12.939733,-8.254199,-9.137238,-14.254726,-9.220370,-6.377359,-3.576869,rates_averted
598,522,0.8,2025,zero industry wheat,-16.723388,-10.583670,-8.279414,-8.816180,-22.048993,-19.283938,...,-7.756615,-16.757803,-20.742538,-13.223954,-14.638492,-22.856634,-14.771614,-10.216715,-5.725816,rates_averted
599,522,1.0,2025,zero industry wheat,-20.930791,-13.239901,-10.354725,-11.026241,-27.603176,-24.134181,...,-9.701503,-20.969236,-25.960643,-16.544308,-18.313874,-28.611689,-18.480367,-12.781680,-7.159624,rates_averted

In [21]:
y = pd.read_pickle(iron_u5_results_path)
y

draw,location_id,coverage_level,year,vehicle,draw_0,draw_1,draw_10,draw_100,draw_101,draw_102,...,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999,measure
0,6,0.2,2025,industry wheat,6.394933,2.343036,3.264021,1.889394,6.099295,5.016220,...,2.930081,6.472833,7.909899,2.277403,4.335902,11.760010,3.233146,3.712411,3.475743,pif
1,6,0.5,2025,industry wheat,14.975322,5.708617,7.939372,4.632439,14.489039,11.959095,...,7.099944,15.122566,18.435089,5.571873,10.421399,27.831902,7.899147,9.001633,8.492461,pif
2,6,0.8,2025,industry wheat,22.484278,8.904114,12.363614,7.270039,22.053413,18.262833,...,11.015200,22.661122,27.552965,8.726392,16.040117,42.217856,12.353355,13.975274,13.282175,pif
3,6,1.0,2025,industry wheat,26.966619,10.944587,15.180889,8.971922,26.681654,22.140738,...,13.492242,27.148930,32.949893,10.754880,19.545161,50.970627,15.209854,17.126090,16.354219,pif
4,6,0.2,2025,wheat flour,3.221340,1.037210,1.808838,1.025055,4.172969,3.147165,...,1.843748,4.241484,4.604619,0.967990,2.579024,8.475886,1.415439,2.410672,2.029698,pif
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1591,522,1.0,2025,zero maize flour,-10.690245,-12.057816,-7.551882,-8.761066,-14.600126,-14.848382,...,-11.950550,-16.220443,-37.191927,-9.918560,-12.999156,-30.457278,-18.601387,-8.507799,-7.963798,rates_averted
1592,522,0.2,2025,zero wheat flour,-4.164923,-2.639730,-2.066579,-2.200436,-5.487101,-4.803434,...,-1.935714,-4.176262,-5.166152,-3.297371,-3.650168,-5.689624,-3.683392,-2.547710,-1.430041,rates_averted
1593,522,0.5,2025,zero wheat flour,-10.432208,-6.607059,-5.170541,-5.505601,-13.749180,-12.030521,...,-4.843584,-10.457141,-12.939733,-8.254199,-9.137238,-14.254726,-9.220370,-6.377359,-3.576869,rates_averted
1594,522,0.8,2025,zero wheat flour,-16.723388,-10.583670,-8.279414,-8.816180,-22.048993,-19.283938,...,-7.756615,-16.757803,-20.742538,-13.223954,-14.638492,-22.856634,-14.771614,-10.216715,-5.725816,rates_averted
1595,522,1.0,2025,zero wheat flour,-20.930791,-13.239901,-10.354725,-11.026241,-27.603176,-24.134181,...,-9.701503,-20.969236,-25.960643,-16.544308,-18.313874,-28.611689,-18.480367,-12.781680,-7.159624,rates_averted

In [22]:
x.vehicle.unique()

array(['industry wheat', 'zero industry wheat'], dtype=object)

In [23]:
y.vehicle.unique()

array(['industry wheat', 'wheat flour', 'zero industry wheat',
       'zero wheat flour', 'maize flour', 'zero maize flour'],
      dtype=object)

In [28]:
x

draw,location_id,coverage_level,year,vehicle,draw_0,draw_1,draw_10,draw_100,draw_101,draw_102,...,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999,measure
0,6,0.2,2025,industry wheat,3.214088,1.118524,1.684095,0.965343,3.480620,2.737738,...,1.596346,3.621688,4.199178,1.072679,2.307565,6.923879,1.537115,2.053347,1.829435,pif
1,6,0.5,2025,industry wheat,7.777186,2.762206,4.151225,2.389536,8.452598,6.670246,...,3.923702,8.719056,10.117121,2.654606,5.649876,16.761471,3.801178,5.047455,4.518938,pif
2,6,0.8,2025,industry wheat,12.048928,4.365913,6.549429,3.785649,13.141853,10.403356,...,6.173010,13.442606,15.608101,4.204651,8.854652,25.981634,6.016235,7.941823,7.144208,pif
3,6,1.0,2025,industry wheat,14.744571,5.413359,8.110969,4.701071,16.119469,12.786432,...,7.630569,16.398815,19.047411,5.220647,10.917632,31.806669,7.466224,9.817803,8.859441,pif
4,6,0.2,2025,zero industry wheat,-0.444387,-0.140759,-0.246195,-0.139023,-0.576749,-0.433155,...,-0.251820,-0.590484,-0.639088,-0.131144,-0.353225,-1.175903,-0.191889,-0.329320,-0.275872,pif
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,522,1.0,2025,industry wheat,257.005440,137.978019,118.841408,111.666940,242.552024,236.646736,...,117.002905,260.784254,308.463213,146.792945,197.258925,267.463796,171.493759,123.774497,101.862440,rates_averted
596,522,0.2,2025,zero industry wheat,-4.164923,-2.639730,-2.066579,-2.200436,-5.487101,-4.803434,...,-1.935714,-4.176262,-5.166152,-3.297371,-3.650168,-5.689624,-3.683392,-2.547710,-1.430041,rates_averted
597,522,0.5,2025,zero industry wheat,-10.432208,-6.607059,-5.170541,-5.505601,-13.749180,-12.030521,...,-4.843584,-10.457141,-12.939733,-8.254199,-9.137238,-14.254726,-9.220370,-6.377359,-3.576869,rates_averted
598,522,0.8,2025,zero industry wheat,-16.723388,-10.583670,-8.279414,-8.816180,-22.048993,-19.283938,...,-7.756615,-16.757803,-20.742538,-13.223954,-14.638492,-22.856634,-14.771614,-10.216715,-5.725816,rates_averted
599,522,1.0,2025,zero industry wheat,-20.930791,-13.239901,-10.354725,-11.026241,-27.603176,-24.134181,...,-9.701503,-20.969236,-25.960643,-16.544308,-18.313874,-28.611689,-18.480367,-12.781680,-7.159624,rates_averted

In [30]:
(
    y
    .query("location_id==214 and year==2025 and measure=='counts_averted' and coverage_level==0.5")
    .groupby('vehicle')
    .count()
)

draw,location_id,coverage_level,year,draw_0,draw_1,draw_10,draw_100,draw_101,draw_102,draw_103,...,draw_991,draw_992,draw_993,draw_994,draw_995,draw_996,draw_997,draw_998,draw_999,measure
vehicle,,,,,,,,,,,,,,,,,,,,,
industry wheat,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
maize flour,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
wheat flour,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
zero industry wheat,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
zero maize flour,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
zero wheat flour,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [41]:
x.vehicle.unique()

array(['industry wheat', 'zero industry wheat'], dtype=object)

In [39]:
x.coverage_level.unique()

array([0.2, 0.5, 0.8, 1. ])